### ISSUE TITLE
Run Lighthouse check 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#10]
Run lighthouse check on the website.

**Comment by liambrewster** [comment]
**Mobile test results**

![Screenshot 2021-06-06 at 21 45 24](https://user-images.githubusercontent.com/31896214/120939573-8f267b00-c710-11eb-9991-0fa41177c8eb.png)

Pdf report Here -> [mobile lighthouse test.pdf](https://github.com/Evavic44/Hotel-Zeitaku/files/6604903/mobile.lighthouse.test.pdf)

**Comment by liambrewster** [comment]
**Desktop test results**


![Screenshot 2021-06-06 at 21 49 34](https://user-images.githubusercontent.com/31896214/120939727-3d322500-c711-11eb-8500-805818ae0908.png)

Pdf report Here -> [desktop lighthouse test.pdf](https://github.com/Evavic44/Hotel-Zeitaku/files/6604908/desktop.lighthouse.test.pdf)

**Comment by liambrewster** [comment]
fixed

**Comment by Evavic44** [comment]
> 
> 
> fixed

Thanks. Now those are some low scores.

**Comment by Evavic44** [comment]
Next thing is to raise issues to improve the scores
