### ISSUE TITLE
Convert all px units in `style.css` to rem units

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#12]
Conversion  `formula`
```css
 value in px / 16px = rem
```
On the `style.css` file, change the pixel values to rem units. For better accessibility and responsiveness

**Comment by skpandey885** [comment]
Hey, Can I Fix This Issue?

**Comment by Evavic44** [comment]
> 
> 
> Hey, Can I Fix This Issue?

I'll assign you to this.

**Comment by skpandey885** [comment]
hey how can i contact you in case of any doubt

**Comment by skpandey885** [comment]
Hey! I Have Fixed This Issue (in The main Branch) And Uploaded it At My Profile! But I am Unable To Generate A Pull Request Due To Some Branch Related Stuff! help Me asap!

**Comment by Evavic44** [comment]
My contact links are in my Github page. [Here](https://github.com/Evavic44)
