### ISSUE TITLE
Add link attribute

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#14]
Add the attribute below to all external links on the `.html` file
```css
rel="noreferrer noopener"
```

E.g 
```css
<li><a href="https://web.facebook.com/evavic44" rel="noreferrer noopener"><i class="fab fa-facebook"></i></a></li>
```

**Comment by briankarlsayen** [comment]
Hi, may I work on this? It's my first time contributing to open source. Thanks!

**Comment by Evavic44** [comment]
> Hi, may I work on this? It's my first time contributing to open source. Thanks!

Sure, go ahead.
