### ISSUE TITLE
Rooms images should be made a hyperlink, cursor should change to pointer when you hover over rooms images.

### ISSUE THREAD

**Issue by GaurPeeyush** [Evavic44/Hotel-Zeitaku#18]
Changing room images into respective hyperlinks would make it more convenient for the users to use. 
Henceforth would make the website more aesthetic.

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue!
kindly assign :)

**Comment by Evavic44** [comment]
That sounds like a good idea, sure, go ahead. But I will review it before merging.

**Comment by GaurPeeyush** [comment]
> That sounds like a good idea, sure, go ahead. But I will review it before merging.

Kindly assign me :)

**Comment by GaurPeeyush** [comment]
I've updated index.html with reference to this issue.
All the room images are made hyperlinks and the cursor changes to the pointer when you hover over the rooms.
Kindly review the code and merge the pull request :)
