### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Hotel-Zeitaku#7]
#### Steps
- [x] Extract the `zip` file provided below which contains the favicon images and web manifest file.
- [x] Paste the extracted folder into the [img](https://github.com/Evavic44/Hotel-Zeitaku/tree/master/img) folder in the root directory of the website.
- [x] Copy and paste the following code to the head of the [index.html](https://github.com/Evavic44/Hotel-Zeitaku/blob/master/index.html) file, [about.html](https://github.com/Evavic44/Hotel-Zeitaku/blob/master/about.html), and [thankyou.html](https://github.com/Evavic44/Hotel-Zeitaku/blob/master/thankyou.html) file.

#### Code 
```html

<!-- Favicon --> 
<link rel="apple-touch-icon" sizes="180x180" href="./img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="./img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="./img/favicon/favicon-16x16.png">
<link rel="icon" sizes="192x192" href="./img/favicon/android-chrome-192x192.png">
<link rel="icon" sizes="512x512" href="./img/favicon/android-chrome-512x512.png">
<link rel="manifest" href="img/favicon/site.webmanifest">
```
#### Zip file
[favicon_io.zip](https://github.com/Evavic44/Hotel-Zeitaku/files/6601957/favicon_io.zip)

**Comment by jaredwelch** [comment]
@Evavic44 , I've created a pull request with the requested changes:
https://github.com/Evavic44/Hotel-Zeitaku/pull/8
